name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f pnpm-lock.yaml ]; then
            echo "pnpm" > pm.txt
          elif [ -f yarn.lock ]; then
            echo "yarn" > pm.txt
          else
            echo "npm" > pm.txt
          fi
        shell: bash

      - name: Read detected package manager
        id: read-pm
        run: echo "manager=$(cat pm.txt)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.read-pm.outputs.manager }}

      - name: Setup pnpm
        if: ${{ steps.read-pm.outputs.manager == 'pnpm' }}
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml', '**/yarn.lock', '**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml', '**/yarn.lock', '**/package-lock.json') }}-

      - name: Install dependencies
        run: |
          if [ "${{ steps.read-pm.outputs.manager }}" = "pnpm" ]; then
            pnpm install
          elif [ "${{ steps.read-pm.outputs.manager }}" = "yarn" ]; then
            yarn install
          else
            npm install --legacy-peer-deps
          fi

      - name: Build site
        run: npx next build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
